spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eduwise?currentSchema=eduwise
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 3000
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: eduwise
  mail:
    host: smtp.gmail.com
    port: 587
    username: ismataga1@gmail.com
    password: sizjabbnhdtfvjgp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    user:
      name: ismat



  liquibase:
    enabled: true

